version: "3.7"

services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  app-a:
    image: golang:latest
    container_name: service-a
    depends_on:
      - zipkin-all-in-one
      - otel-collector
    volumes:
      - ./service-a:/go/src/app
    command: ["tail", "-f", "/dev/null"]
    # build: 
    #   context: ./service-a
    #   dockerfile: Dockerfile
    # container_name: service-a
    # ports:
    #   - "8081:8081"
    # volumes:
    #   - ./service-a:/go/src/

  app-b:
    image: golang:latest
    container_name: service-b
    depends_on:
      - zipkin-all-in-one
      - otel-collector
    volumes:
      - ./service-b:/go/src/app
    command: ["tail", "-f", "/dev/null"]
    # build: 
    #   context: ./service-b
    #   dockerfile: Dockerfile
    # container_name: service-b
    # ports:
    #   - "8082:8082"
    # volumes:
    #   - ./service-b:/go/src/
  