version: "3.7"

services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin-all-in-one
    restart: always
    ports:
      - "9411:9411"

  app-a:
    build: ./service-a
    container_name: service-a
    depends_on:
      - zipkin-all-in-one
    ports:
      - "8081:8081"
    volumes:
      - ./service-a:/app
    # command: ["tail", "-f", "/dev/null"]

  app-b:
    build: ./service-b
    container_name: service-b
    depends_on:
      - zipkin-all-in-one
    ports:
      - "8082:8082"
    volumes:
      - ./service-b:/app
    # command: ["tail", "-f", "/dev/null"]
  