receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: zipkin-all-in-one:9411
    tls:
      insecure: true
 
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]